#!/bin/bash
# -*- coding:utf-8 -*-
PASS_ENTER_TO_EXIT(){
	$cn && InfoMsg="请按回车后退出，否则15秒内自动退出。" || InfoMsg="input enter or wait 15s to exit"
	read -p "$InfoMsg" -t 15 ok
}
TEST_FILE(){
	if [ ! -f $1 ];then
		echo "Not exist $1"
		PASS_ENTER_TO_EXIT
		SELECT_RUN_SCRIPT
	else
		echo "loading $1 now..."
	fi
}
TEST_PROGRAMS(){
	for arg do
		if [ -z $(which $arg) ];then
			read -p "Your system do not have $arg" -t 10 ok
			return 0
		else
			read -p "loading $arg ..." -t 1 ok
		fi
	done
}
INPUT_CHOOSE(){
	VarTmp=
	select vars in $@ "exit"; do
		case $vars in
			$vars)
				[ "$vars" == "exit" ] && VarTmp="" || VarTmp="$vars"
				break;;
		esac
		echo "Input again"
	done
}
